# Generated by Django 4.0.6 on 2024-05-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('class_1', models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'Introduction to Stochastic Processes and their Applications'), ('PHY431', 'Quantum Mechanics I'), ('PHY432', 'Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True)),
                ('attendence_class_1', models.IntegerField(blank=True, null=True)),
                ('class_2', models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'Introduction to Stochastic Processes and their Applications'), ('PHY431', 'Quantum Mechanics I'), ('PHY432', 'Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True)),
                ('attendence_class_2', models.IntegerField(blank=True, null=True)),
                ('class_3', models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'Introduction to Stochastic Processes and their Applications'), ('PHY431', 'Quantum Mechanics I'), ('PHY432', 'Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True)),
                ('attendence_class_3', models.IntegerField(blank=True, null=True)),
                ('class_4', models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'Introduction to Stochastic Processes and their Applications'), ('PHY431', 'Quantum Mechanics I'), ('PHY432', 'Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True)),
                ('attendence_class_4', models.IntegerField(blank=True, null=True)),
                ('class_5', models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'Introduction to Stochastic Processes and their Applications'), ('PHY431', 'Quantum Mechanics I'), ('PHY432', 'Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True)),
                ('attendence_class_5', models.IntegerField(blank=True, null=True)),
                ('class_6', models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'Introduction to Stochastic Processes and their Applications'), ('PHY431', 'Quantum Mechanics I'), ('PHY432', 'Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True)),
                ('attendence_class_6', models.IntegerField(blank=True, null=True)),
                ('class_7', models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'Introduction to Stochastic Processes and their Applications'), ('PHY431', 'Quantum Mechanics I'), ('PHY432', 'Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True)),
                ('attendence_class_7', models.IntegerField(blank=True, null=True)),
                ('class_8', models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'Introduction to Stochastic Processes and their Applications'), ('PHY431', 'Quantum Mechanics I'), ('PHY432', 'Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True)),
                ('attendence_class_8', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
