# Generated by Django 4.0.6 on 2024-05-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_1',
            field=models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'DMS625: Introduction to Stochastic Processes and their Applications'), ('PHY431', 'PHY431: Quantum Mechanics I'), ('PHY432', 'PHY432: Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_2',
            field=models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'DMS625: Introduction to Stochastic Processes and their Applications'), ('PHY431', 'PHY431: Quantum Mechanics I'), ('PHY432', 'PHY432: Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_3',
            field=models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'DMS625: Introduction to Stochastic Processes and their Applications'), ('PHY431', 'PHY431: Quantum Mechanics I'), ('PHY432', 'PHY432: Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_4',
            field=models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'DMS625: Introduction to Stochastic Processes and their Applications'), ('PHY431', 'PHY431: Quantum Mechanics I'), ('PHY432', 'PHY432: Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_5',
            field=models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'DMS625: Introduction to Stochastic Processes and their Applications'), ('PHY431', 'PHY431: Quantum Mechanics I'), ('PHY432', 'PHY432: Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_6',
            field=models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'DMS625: Introduction to Stochastic Processes and their Applications'), ('PHY431', 'PHY431: Quantum Mechanics I'), ('PHY432', 'PHY432: Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_7',
            field=models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'DMS625: Introduction to Stochastic Processes and their Applications'), ('PHY431', 'PHY431: Quantum Mechanics I'), ('PHY432', 'PHY432: Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_8',
            field=models.CharField(blank=True, choices=[('MTH113', 'MTH113: Linear Algebra'), ('MTH114', 'MTH114: Ordinary Differential Equations'), ('ESO207', 'ESO207: Data Structures and Algorithms'), ('CS771', 'CS771: Introduction to Machine Learning'), ('MSO205', 'MSO205: Introduction to Probability Theory'), ('DMS625', 'DMS625: Introduction to Stochastic Processes and their Applications'), ('PHY431', 'PHY431: Quantum Mechanics I'), ('PHY432', 'PHY432: Quantum Mechanics II'), ('EE798I', 'EE798I: Nanophotonics'), ('EE798Z', 'EE798Z: Mathematical Engineering and Physics using Machine Learning')], max_length=6, null=True),
        ),
    ]
