# Generated by Django 4.0.6 on 2024-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_alter_student_class_1_alter_student_class_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('class_1', models.DateTimeField(blank=True)),
                ('class_2', models.DateTimeField(blank=True)),
                ('class_3', models.DateTimeField(blank=True)),
                ('class_4', models.DateTimeField(blank=True)),
                ('class_5', models.DateTimeField(blank=True)),
                ('total_classes', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='attendence_class_1',
            new_name='attendence_course_1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='attendence_class_2',
            new_name='attendence_course_2',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='attendence_class_3',
            new_name='attendence_course_3',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='attendence_class_4',
            new_name='attendence_course_4',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='attendence_class_5',
            new_name='attendence_course_5',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='attendence_class_6',
            new_name='attendence_course_6',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='attendence_class_7',
            new_name='attendence_course_7',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='attendence_class_8',
            new_name='attendence_course_8',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_1',
            new_name='course_1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_2',
            new_name='course_2',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_3',
            new_name='course_3',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_4',
            new_name='course_4',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_5',
            new_name='course_5',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_6',
            new_name='course_6',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_7',
            new_name='course_7',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_8',
            new_name='course_8',
        ),
    ]
