# Generated by Django 4.0.6 on 2024-05-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendence_course_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendence_course_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendence_course_3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendence_course_4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendence_course_5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendence_course_6',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendence_course_7',
        ),
        migrations.RemoveField(
            model_name='student',
            name='attendence_course_8',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_6',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_7',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_8',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='bruh', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='total_attendence',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='attendence.course'),
        ),
    ]
