# Generated by Django 4.0.6 on 2024-05-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_remove_student_attendence_course_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_4',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_5',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
