# Generated by Django 4.0.6 on 2024-05-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_alter_course_class_1_alter_course_class_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_attendence',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='bruh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='lmao', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='lmao', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='total_classes',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
