# Generated by Django 4.0.6 on 2024-05-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0006_remove_course_total_attendence_remove_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
