# Generated by Django 4.0.6 on 2024-05-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0008_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='attendance',
            new_name='course_attendance',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_5',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_classes',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.course')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.classsession')),
            ],
            options={
                'unique_together': {('enrollment', 'session')},
            },
        ),
    ]
