# Generated by Django 4.0.6 on 2024-05-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0009_rename_attendance_enrollment_course_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='total_classes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
